### ISSUE TITLE
[ERROR] Making DMG from template:

### ISSUE THREAD

**Issue by ruihuowayking** [kettek/go-apper#1]
2019/02/21 14:25:05 [ERROR] Making DMG from template: making copy of template DMG: stat uitest.dmg: no such file or directory

Why?

**Comment by kettek** [comment]
I'll preface this response with the fact that I have not personally used the DMG templating functionality, but as far as the code goes it just attempts to open the location you provide relative to your current directory. So:

  1. Ensure your DMG file `uitest.dmg` is in the same location as you're running.
  2. Or specify an absolute path to `uitest.dmg`, such as `-dmg /Users/YourUser/uitest.dmg`

**Comment by kettek** [comment]
Will be closing within a few days due to likelihood of incorrect path specification alongside a lack of response.
